// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/data/productos.ts
var productosAlmacenamiento = [
  {
    id: 1,
    name: "Silos de Fondo Plano EVO 50",
    description: "Para cumplir con las diversas aplicaciones requeridas, GSI ofrece una completa l\xEDnea de silos de almacenamiento ventilados de fondo plano. Esta l\xEDnea abarca capacidades desde 90 m\xB3 hasta 41.165 m\xB3, adapt\xE1ndose a las necesidades espec\xEDficas de cada productor.",
    image: "/lovable-uploads/bb3e9329-ad88-485a-a354-d83f8632994f.webp",
    specs: [
      "Capacidades desde 90 m\xB3 hasta 41.165 m\xB3",
      "Sistema de ventilaci\xF3n integrado",
      "Dise\xF1o vers\xE1til para diversas aplicaciones",
      "Construcci\xF3n robusta con est\xE1ndares de calidad GSI"
    ]
  },
  {
    id: 2,
    name: "Silos de Fondo C\xF3nico EVO 50",
    description: "Los silos de fondo c\xF3nico EVO 50 de GSI ofrecen mayor agilidad en la descarga, optimizando el flujo de granos y reduciendo tiempos de operaci\xF3n. Su dise\xF1o c\xF3nico facilita la descarga completa del producto almacenado.",
    image: "/lovable-uploads/bb0c281c-6e9a-48ed-b2ab-bc5a3251358d.webp",
    specs: [
      "Dise\xF1o c\xF3nico que facilita la descarga completa",
      "Mayor eficiencia en el manejo de granos",
      "Construcci\xF3n duradera con tecnolog\xEDa EVO 50",
      "Ideal para operaciones que requieren descargas frecuentes"
    ]
  },
  {
    id: 3,
    name: "Roscas Barredoras",
    description: "Las roscas barredoras de GSI ofrecen la tecnolog\xEDa que su propiedad necesita para almacenar granos de manera segura y lograr mejores resultados. Son capaces de auxiliar en la descarga de silos y brindan agilidad, eficiencia y robustez, minimizando el acceso del operador al interior de los silos.",
    image: "/lovable-uploads/f4497456-6eea-475d-a974-9e593bebc184.webp",
    specs: [
      "Tecnolog\xEDa avanzada para descarga eficiente",
      "Mayor seguridad al minimizar el acceso del operador al interior",
      "Robustez y durabilidad",
      "Mejora la eficiencia operativa",
      "Compatible con los sistemas de silos GSI"
    ]
  },
  {
    id: 4,
    name: "Esparcidor de Granos",
    description: "El esparcidor de granos GSI asegura una distribuci\xF3n uniforme del grano dentro del silo, optimizando el espacio de almacenamiento y mejorando la aireaci\xF3n. Esto contribuye a una mejor conservaci\xF3n del grano y a la prevenci\xF3n de puntos calientes.",
    image: "/lovable-uploads/b1109187-68a8-45ef-b7c0-959aed07cfe3.webp",
    specs: [
      "Distribuci\xF3n uniforme del grano",
      "Optimizaci\xF3n del espacio de almacenamiento",
      "Mejora la aireaci\xF3n",
      "Contribuye a la conservaci\xF3n del grano",
      "Previene puntos calientes"
    ]
  }
];
var productosSecado = [
  {
    id: 5,
    name: "Process Dryer",
    description: "Secadora de granos con tecnolog\xEDa original GSI y sistema de secado continuo con flujo de aire cruzado, proporciona granos secos con calidad superior. Fue desarrollada para trabajar con diferentes tipos de granos, ya sea con fines comerciales o para la producci\xF3n de semillas.",
    image: "/lovable-uploads/d1e07e63-b4f8-48b3-9a56-1baef2ced2e9.webp",
    specs: [
      "Tecnolog\xEDa original GSI",
      "Sistema de secado continuo con flujo de aire cruzado",
      "Calidad superior de secado",
      "Versatilidad para diferentes tipos de granos",
      "Mantiene la integridad del grano",
      "Ideal tanto para uso comercial como para producci\xF3n de semillas"
    ]
  },
  {
    id: 6,
    name: "Sistema de Aireaci\xF3n y Ventiladores",
    description: "Los sistemas de aireaci\xF3n de los silos GSI se dimensionan de acuerdo al producto almacenado y a la tasa de aireaci\xF3n (flujo de aire) necesaria para la conservaci\xF3n del grano. Se encuentran disponibles sistemas de aireaci\xF3n de canal y de piso 100% perforado.",
    image: "/lovable-uploads/e35fc5b9-1b54-4cb1-81e6-bc564e15499b.webp",
    specs: [
      "Dimensionamiento personalizado seg\xFAn el producto almacenado",
      "Adaptaci\xF3n a la tasa de aireaci\xF3n necesaria",
      "Disponible en sistemas de canal y de piso 100% perforado",
      "Dise\xF1ado para la \xF3ptima conservaci\xF3n del grano",
      "Compatible con los sistemas de silos GSI"
    ]
  },
  {
    id: 7,
    name: "Portable Dryers",
    description: "Las secadoras port\xE1tiles GSI ofrecen flexibilidad y eficiencia para el secado de granos en diferentes ubicaciones. Son ideales para operaciones que requieren movilidad y un secado r\xE1pido y efectivo.",
    image: "/lovable-uploads/9fb7021e-e36f-406c-bf46-205a18fa659c.webp",
    specs: [
      "Flexibilidad y movilidad",
      "Secado r\xE1pido y efectivo",
      "Ideal para diferentes ubicaciones",
      "Construcci\xF3n robusta y duradera",
      "F\xE1cil de operar y mantener"
    ]
  },
  {
    id: 8,
    name: "TopDry",
    description: "El sistema TopDry de GSI combina el secado y el almacenamiento en una sola unidad, ofreciendo una soluci\xF3n compacta y eficiente para el manejo de granos. Permite secar y enfriar el grano antes de almacenarlo, optimizando el proceso.",
    image: "/lovable-uploads/5455be7f-63a4-40ec-9625-1b637a5f7c88.webp",
    specs: [
      "Combina secado y almacenamiento en una unidad",
      "Soluci\xF3n compacta y eficiente",
      "Secado y enfriamiento del grano antes del almacenamiento",
      "Optimiza el proceso de manejo de granos",
      "Reduce la necesidad de equipos adicionales"
    ]
  }
];
var productosManejo = [
  {
    id: 9,
    name: "Elevadores",
    description: "Fabricados con componentes de alta calidad y construcci\xF3n robusta, los elevadores de granos GSI cuentan con alta durabilidad, operaci\xF3n continua y la mejor relaci\xF3n costo-beneficio para su producci\xF3n.",
    image: "/lovable-uploads/78866758-f51a-4f00-942d-d37f9de1a6c0.webp",
    specs: [
      "Componentes de alta calidad",
      "Construcci\xF3n robusta",
      "Alta durabilidad",
      "Operaci\xF3n continua",
      "Excelente relaci\xF3n costo-beneficio",
      "Dise\xF1ados para uso intensivo en operaciones agroindustriales"
    ]
  },
  {
    id: 10,
    name: "Transportadores de Cadena",
    description: "Los transportadores de cadena GSI son extremadamente eficientes para el transporte de los granos en forma horizontal o vertical en la planta almacenadora, optimizando el flujo de material y reduciendo tiempos de operaci\xF3n.",
    image: "/lovable-uploads/8f3ff249-d04c-490d-992d-74aa1b0b272b.webp",
    specs: [
      "Alta eficiencia en el transporte de granos",
      "Versatilidad para transporte horizontal o vertical",
      "Dise\xF1o robusto para plantas almacenadoras",
      "Integraci\xF3n perfecta con otros sistemas GSI",
      "Optimizaci\xF3n del flujo de granos en la planta"
    ]
  },
  {
    id: 11,
    name: "Cintas/Correas Transportadoras",
    description: "La tecnolog\xEDa aplicada en los mayores proyectos de almacenamiento globales llega a usted a trav\xE9s de dos l\xEDneas de cintas/correas GSI. Estos modelos emplean una soluci\xF3n inteligente, silenciosa y vers\xE1til para el transporte de granos horizontal e inclinado en distancias cortas, medias y largas.",
    image: "/lovable-uploads/f3419807-79a8-4523-9743-9cb6795e00db.webp",
    specs: [
      "Tecnolog\xEDa de nivel mundial",
      "Soluci\xF3n inteligente y silenciosa",
      "Versatilidad para transporte horizontal e inclinado",
      "Adaptable a distancias cortas, medias y largas",
      "Dise\xF1o eficiente para minimizar el da\xF1o al grano",
      "Operaci\xF3n silenciosa para mejor ambiente de trabajo"
    ]
  },
  {
    id: 12,
    name: "M\xE1quina de Prelimpieza",
    description: "Las m\xE1quinas de prelimpieza de GSI separan las impurezas de todo tipo de granos, mejorando la calidad del producto almacenado y reduciendo riesgos de contaminaci\xF3n durante el almacenamiento.",
    image: "/lovable-uploads/2d924d1b-1e2d-4145-8f7c-a101eb817498.webp",
    specs: [
      "Separaci\xF3n eficiente de impurezas",
      "Compatible con diversos tipos de granos",
      "Mejora la calidad del producto almacenado",
      "Reduce riesgos de contaminaci\xF3n",
      "Optimiza el proceso de almacenamiento",
      "Prolonga la vida \xFAtil del grano almacenado"
    ]
  }
];
var productosBalanzas = [
  {
    id: 13,
    name: "Balanza Camionera Met\xE1lica",
    description: "Totalmente modular, compuesto por una estructura met\xE1lica (acero). Construido seg\xFAn las normas ABNT para carga m\xF3vil en puentes de carretera. Fabricado con un estricto control de calidad utilizando materias primas y componentes electr\xF3nicos de primera calidad. Disponible en varias capacidades, de 40.000 a 200.000 kg, con plataformas de 12 a 60 m. Versiones: SP = sobre el suelo con rampa; SE = semiempotrado sin rampa y totalmente empotrado.",
    image: "/lovable-uploads/4f443edd-e4b5-4b4d-9e92-deb3d8a532a8.webp",
    specs: [
      "Construcci\xF3n met\xE1lica robusta y duradera",
      "Alta precisi\xF3n en el pesaje de veh\xEDculos pesados",
      "Dise\xF1o espec\xEDfico para la industria agr\xEDcola",
      "Sistema de pesaje confiable para granos",
      "Resistente a condiciones clim\xE1ticas adversas",
      "Marca Coimma con garant\xEDa de calidad"
    ]
  },
  {
    id: 14,
    name: "Balanza de Concreto",
    description: "Plataforma dise\xF1ada para recibir una cubierta de hormig\xF3n, dise\xF1ada seg\xFAn las Normas ABNT - Carga M\xF3vil en Puentes de Carretera. Fabricada con materias primas y componentes electr\xF3nicos de primera calidad, se ofrece en diversas capacidades, desde 40.000 hasta 200.000 kg, y con plataformas de 10 a 60 m. Versiones: SP = sobre el suelo con rampa; SE = semiempotrada sin rampa y totalmente empotrada.",
    image: "/lovable-uploads/29929e96-1389-43a3-a961-7fa37fb2c856.webp",
    specs: [
      "Construcci\xF3n en concreto armado para m\xE1xima estabilidad",
      "Soluci\xF3n permanente para pesaje industrial",
      "Resistencia superior a cargas pesadas",
      "Ideal para operaciones de pesaje continuo",
      "M\xEDnimo mantenimiento requerido",
      "Tecnolog\xEDa Coimma de precisi\xF3n garantizada"
    ]
  }
];
var productosVolcadoras = [
  {
    id: 15,
    name: "Plataforma Volcadora Trasera 21 metros",
    description: "La Plataforma de Volcadora Trasera SAUR de 21 metros fue proyectada para descargar camiones tolvas, chatos, carretas, bitrenes y rodotrenes de hasta 90 toneladas. La descarga se realiza de forma simple y pr\xE1ctica, en un promedio de 4 minutos, lo que contribuye con el proceso y reduce considerablemente las filas en las centrales de recepci\xF3n. \xC9ste es uno de los modelos m\xE1s comunes y est\xE1 entre los sistemas de descarga de graneles m\xE1s vendidos.",
    image: "/lovable-uploads/55c80e54-aae9-498a-b272-583d3f81db08.webp",
    specs: [
      "Capacidad de carga: 80 o 90 Ton.",
      "Largo: 21.000 mm",
      "Ancho: 3.000 mm",
      "\xC1ngulo de basculado: 40\xB0",
      "Para descarga de camiones tolva, chatos, carretas, bitrenes y rodotrenes de hasta 90 toneladas",
      "Posibilidad de adaptaci\xF3n de Balanza Electr\xF3nica Integrada",
      "Cilindros internos para obras que previenen instalaci\xF3n de la Plataforma o cilindros externos para obras existentes y versi\xF3n m\xF3vil"
    ]
  },
  {
    id: 16,
    name: "Colectores de Muestras",
    description: "Los colectores de muestras Saur son equipos especializados para la toma autom\xE1tica de muestras de granos durante el proceso de descarga. Garantizan muestras representativas y consistentes, esenciales para el control de calidad en la recepci\xF3n de granos.",
    image: "/lovable-uploads/449f003e-565b-4dc5-b50b-6f477d499a6e.webp",
    specs: [
      "Toma autom\xE1tica de muestras representativas",
      "Sistema especializado para granos",
      "Control de calidad en recepci\xF3n",
      "Operaci\xF3n autom\xE1tica y consistente",
      "Dise\xF1o robusto para uso industrial",
      "Marca Saur con tecnolog\xEDa especializada"
    ]
  }
];

// src/lib/mcp/tools/list-products.ts
var CATEGORIES = {
  almacenamiento: productosAlmacenamiento,
  secado: productosSecado,
  manejo: productosManejo,
  balanzas: productosBalanzas,
  volcadoras: productosVolcadoras
};
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar productos",
  description: "Lista el cat\xE1logo de productos GSI de Almatec SRL (silos, secadoras, manejo de granos, balanzas y volcadoras), opcionalmente filtrado por categor\xEDa.",
  inputSchema: {
    category: z.enum(["almacenamiento", "secado", "manejo", "balanzas", "volcadoras"]).optional().describe("Categor\xEDa de producto a listar. Si se omite, devuelve todas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const entries = category ? [[category, CATEGORIES[category]]] : Object.entries(CATEGORIES);
    const products = entries.flatMap(
      ([cat, items]) => items.map((p) => ({
        category: cat,
        name: p.name,
        description: p.description,
        specs: p.specs
      }))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { count: products.length, products }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/config/contact.ts
var ALMATEC_PHONES = [
  {
    raw: "+59177028610",
    display: "77028610",
    displayFull: "(+591) 77028610"
  },
  {
    raw: "+59178007220",
    display: "78007220",
    displayFull: "(+591) 78007220"
  }
];
var ALMATEC_PRIMARY_PHONE = ALMATEC_PHONES[0];
var ALMATEC_EMAILS = {
  primary: "edson_gsi@hotmail.com",
  secondary: "pabloarteaga@almatec.net"
};
var ALMATEC_ADDRESS = {
  line1: "Av. Banzer entre 4to y 5to anillo",
  line2: "Comercial Plaza Norte, Oficina 46",
  city: "Santa Cruz de la Sierra, Bolivia"
};
var ALMATEC_BUSINESS_HOURS = {
  weekdays: { label: "Lunes a Viernes", hours: "8:00 \u2013 18:00" },
  saturday: { label: "S\xE1bados", hours: "8:00 \u2013 12:00" }
};
var ALMATEC_SOCIAL = {
  facebook: "https://www.facebook.com/almatecscz/?locale=es_LA",
  instagram: "https://www.instagram.com/almatecsrl/",
  linkedin: "https://www.linkedin.com/company/almatec-srl/",
  youtube: "https://www.youtube.com/@GSI.americadelsur"
};
var ALMATEC_SITE_URL = "https://almatecsrl-sitio-web.lovable.app";

// src/lib/mcp/tools/get-company-info.ts
var get_company_info_default = defineTool2({
  name: "get_company_info",
  title: "Informaci\xF3n de la empresa",
  description: "Devuelve los datos oficiales de contacto de Almatec SRL: tel\xE9fonos, correos, direcci\xF3n, horarios, redes sociales y sitio web.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Almatec SRL",
      website: ALMATEC_SITE_URL,
      phones: ALMATEC_PHONES.map((p) => p.displayFull),
      emails: ALMATEC_EMAILS,
      address: ALMATEC_ADDRESS,
      businessHours: ALMATEC_BUSINESS_HOURS,
      social: ALMATEC_SOCIAL
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-contact-inquiries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-contact-inquiries.ts
var list_contact_inquiries_default = defineTool3({
  name: "list_contact_inquiries",
  title: "Listar consultas de contacto",
  description: "Lista las consultas recibidas por el formulario de contacto. Requiere una cuenta con permisos (admin o ventas); RLS filtra el acceso.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Cantidad m\xE1xima de registros.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("contact_inquiries").select("id, created_at, nombre, email, telefono, empresa, asunto, mensaje, ubicacion").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, inquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-quote-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_quote_requests_default = defineTool4({
  name: "list_quote_requests",
  title: "Listar solicitudes de cotizaci\xF3n",
  description: "Lista las solicitudes de cotizaci\xF3n recibidas. Requiere una cuenta con permisos (admin o ventas); RLS filtra el acceso.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Cantidad m\xE1xima de registros.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("quote_requests").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mchbnrqbysucxtsmuqnj";
var mcp_default = defineMcp({
  name: "almatec-mcp",
  title: "Almatec SRL MCP",
  version: "0.1.0",
  instructions: "Herramientas del sitio de Almatec SRL (silos y equipamiento agroindustrial GSI en Bolivia). Usa `list_products` y `get_company_info` para datos del cat\xE1logo y contacto; `list_contact_inquiries` y `list_quote_requests` para consultas y cotizaciones recibidas (solo cuentas con permisos).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_company_info_default, list_contact_inquiries_default, list_quote_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
