// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mchbnrqbysucxtsmuqnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jaGJucnFieXN1Y3h0c211cW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDQ0NDAsImV4cCI6MjA2Njk4MDQ0MH0.PxmLYGE1J2vUW6-Z3IkAlchF0YpBu9xBkCLUVVpP5Js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});